package com.konfigthis.client;

import com.konfigthis.client.api.LegalEntityTaxesApi;
import com.konfigthis.client.api.ApplicantTrackingSystemApi;
import com.konfigthis.client.api.EmployeeLegacyPerformTimeSchedulesApi;
import com.konfigthis.client.api.EmployeeCertificationsApi;
import com.konfigthis.client.api.EmployeeCustomFieldsApi;
import com.konfigthis.client.api.EmployeeDeductionsApi;
import com.konfigthis.client.api.EmployeeDirectDepositsApi;
import com.konfigthis.client.api.EmployeeDocumentsApi;
import com.konfigthis.client.api.EmployeeEarningsApi;
import com.konfigthis.client.api.EmployeeEmergencyContactApi;
import com.konfigthis.client.api.EmployeeI9VerificationApi;
import com.konfigthis.client.api.EmployeeOnboardingApi;
import com.konfigthis.client.api.EmployeePayRatesApi;
import com.konfigthis.client.api.EmployeePayScheduleApi;
import com.konfigthis.client.api.EmployeePayStubsApi;
import com.konfigthis.client.api.EmployeePayrollHoursApi;
import com.konfigthis.client.api.EmployeeTaxesApi;
import com.konfigthis.client.api.EmployeeTimeCardPunchesApi;
import com.konfigthis.client.api.EmployeeTimeOffAccrualsApi;
import com.konfigthis.client.api.EmployeesApi;
import com.konfigthis.client.api.EventsApi;
import com.konfigthis.client.api.GeneralLedgerApi;
import com.konfigthis.client.api.GeneralLedgerJobCostingApi;
import com.konfigthis.client.api.JobTitlesApi;
import com.konfigthis.client.api.LaborCategoriesApi;
import com.konfigthis.client.api.LaborCodesApi;
import com.konfigthis.client.api.LegalEntitiesApi;
import com.konfigthis.client.api.LegalEntityActivityTypesApi;
import com.konfigthis.client.api.LegalEntityCertificationsApi;
import com.konfigthis.client.api.LegalEntityDeductionsApi;
import com.konfigthis.client.api.LegalEntityDepartmentsApi;
import com.konfigthis.client.api.LegalEntityEarningsApi;
import com.konfigthis.client.api.LegalEntityJobTitlesApi;
import com.konfigthis.client.api.LegalEntityPayDataApi;
import com.konfigthis.client.api.LegalEntityPayGroupsApi;
import com.konfigthis.client.api.LegalEntityPayScheduleApi;
import com.konfigthis.client.api.LegalEntityPayrollProcessingDataApi;
import com.konfigthis.client.api.LegalEntityScheduleGroupsApi;
import com.konfigthis.client.api.LegalEntityServicesApi;
import com.konfigthis.client.api.LegalEntityStatusReasonApi;
import com.konfigthis.client.api.LegalEntityTimeDataApi;
import com.konfigthis.client.api.LegalEntityTimeOffTypesApi;
import com.konfigthis.client.api.LegalEntityWorkLocationsApi;
import com.konfigthis.client.api.LegalEntityWorkSitesApi;
import com.konfigthis.client.api.PersonsApi;
import com.konfigthis.client.api.TenantsApi;
import com.konfigthis.client.api.TimeOffRequestsApi;

public class Paycor {
    private ApiClient apiClient;
    public final LegalEntityTaxesApi legalEntityTaxes;
    public final ApplicantTrackingSystemApi applicantTrackingSystem;
    public final EmployeeLegacyPerformTimeSchedulesApi employeeLegacyPerformTimeSchedules;
    public final EmployeeCertificationsApi employeeCertifications;
    public final EmployeeCustomFieldsApi employeeCustomFields;
    public final EmployeeDeductionsApi employeeDeductions;
    public final EmployeeDirectDepositsApi employeeDirectDeposits;
    public final EmployeeDocumentsApi employeeDocuments;
    public final EmployeeEarningsApi employeeEarnings;
    public final EmployeeEmergencyContactApi employeeEmergencyContact;
    public final EmployeeI9VerificationApi employeeI9Verification;
    public final EmployeeOnboardingApi employeeOnboarding;
    public final EmployeePayRatesApi employeePayRates;
    public final EmployeePayScheduleApi employeePaySchedule;
    public final EmployeePayStubsApi employeePayStubs;
    public final EmployeePayrollHoursApi employeePayrollHours;
    public final EmployeeTaxesApi employeeTaxes;
    public final EmployeeTimeCardPunchesApi employeeTimeCardPunches;
    public final EmployeeTimeOffAccrualsApi employeeTimeOffAccruals;
    public final EmployeesApi employees;
    public final EventsApi events;
    public final GeneralLedgerApi generalLedger;
    public final GeneralLedgerJobCostingApi generalLedgerJobCosting;
    public final JobTitlesApi jobTitles;
    public final LaborCategoriesApi laborCategories;
    public final LaborCodesApi laborCodes;
    public final LegalEntitiesApi legalEntities;
    public final LegalEntityActivityTypesApi legalEntityActivityTypes;
    public final LegalEntityCertificationsApi legalEntityCertifications;
    public final LegalEntityDeductionsApi legalEntityDeductions;
    public final LegalEntityDepartmentsApi legalEntityDepartments;
    public final LegalEntityEarningsApi legalEntityEarnings;
    public final LegalEntityJobTitlesApi legalEntityJobTitles;
    public final LegalEntityPayDataApi legalEntityPayData;
    public final LegalEntityPayGroupsApi legalEntityPayGroups;
    public final LegalEntityPayScheduleApi legalEntityPaySchedule;
    public final LegalEntityPayrollProcessingDataApi legalEntityPayrollProcessingData;
    public final LegalEntityScheduleGroupsApi legalEntityScheduleGroups;
    public final LegalEntityServicesApi legalEntityServices;
    public final LegalEntityStatusReasonApi legalEntityStatusReason;
    public final LegalEntityTimeDataApi legalEntityTimeData;
    public final LegalEntityTimeOffTypesApi legalEntityTimeOffTypes;
    public final LegalEntityWorkLocationsApi legalEntityWorkLocations;
    public final LegalEntityWorkSitesApi legalEntityWorkSites;
    public final PersonsApi persons;
    public final TenantsApi tenants;
    public final TimeOffRequestsApi timeOffRequests;

    public Paycor() {
        this(null);
    }

    public Paycor(Configuration configuration) {
        this.apiClient = new ApiClient(null, configuration);
        this.legalEntityTaxes = new LegalEntityTaxesApi(this.apiClient);
        this.applicantTrackingSystem = new ApplicantTrackingSystemApi(this.apiClient);
        this.employeeLegacyPerformTimeSchedules = new EmployeeLegacyPerformTimeSchedulesApi(this.apiClient);
        this.employeeCertifications = new EmployeeCertificationsApi(this.apiClient);
        this.employeeCustomFields = new EmployeeCustomFieldsApi(this.apiClient);
        this.employeeDeductions = new EmployeeDeductionsApi(this.apiClient);
        this.employeeDirectDeposits = new EmployeeDirectDepositsApi(this.apiClient);
        this.employeeDocuments = new EmployeeDocumentsApi(this.apiClient);
        this.employeeEarnings = new EmployeeEarningsApi(this.apiClient);
        this.employeeEmergencyContact = new EmployeeEmergencyContactApi(this.apiClient);
        this.employeeI9Verification = new EmployeeI9VerificationApi(this.apiClient);
        this.employeeOnboarding = new EmployeeOnboardingApi(this.apiClient);
        this.employeePayRates = new EmployeePayRatesApi(this.apiClient);
        this.employeePaySchedule = new EmployeePayScheduleApi(this.apiClient);
        this.employeePayStubs = new EmployeePayStubsApi(this.apiClient);
        this.employeePayrollHours = new EmployeePayrollHoursApi(this.apiClient);
        this.employeeTaxes = new EmployeeTaxesApi(this.apiClient);
        this.employeeTimeCardPunches = new EmployeeTimeCardPunchesApi(this.apiClient);
        this.employeeTimeOffAccruals = new EmployeeTimeOffAccrualsApi(this.apiClient);
        this.employees = new EmployeesApi(this.apiClient);
        this.events = new EventsApi(this.apiClient);
        this.generalLedger = new GeneralLedgerApi(this.apiClient);
        this.generalLedgerJobCosting = new GeneralLedgerJobCostingApi(this.apiClient);
        this.jobTitles = new JobTitlesApi(this.apiClient);
        this.laborCategories = new LaborCategoriesApi(this.apiClient);
        this.laborCodes = new LaborCodesApi(this.apiClient);
        this.legalEntities = new LegalEntitiesApi(this.apiClient);
        this.legalEntityActivityTypes = new LegalEntityActivityTypesApi(this.apiClient);
        this.legalEntityCertifications = new LegalEntityCertificationsApi(this.apiClient);
        this.legalEntityDeductions = new LegalEntityDeductionsApi(this.apiClient);
        this.legalEntityDepartments = new LegalEntityDepartmentsApi(this.apiClient);
        this.legalEntityEarnings = new LegalEntityEarningsApi(this.apiClient);
        this.legalEntityJobTitles = new LegalEntityJobTitlesApi(this.apiClient);
        this.legalEntityPayData = new LegalEntityPayDataApi(this.apiClient);
        this.legalEntityPayGroups = new LegalEntityPayGroupsApi(this.apiClient);
        this.legalEntityPaySchedule = new LegalEntityPayScheduleApi(this.apiClient);
        this.legalEntityPayrollProcessingData = new LegalEntityPayrollProcessingDataApi(this.apiClient);
        this.legalEntityScheduleGroups = new LegalEntityScheduleGroupsApi(this.apiClient);
        this.legalEntityServices = new LegalEntityServicesApi(this.apiClient);
        this.legalEntityStatusReason = new LegalEntityStatusReasonApi(this.apiClient);
        this.legalEntityTimeData = new LegalEntityTimeDataApi(this.apiClient);
        this.legalEntityTimeOffTypes = new LegalEntityTimeOffTypesApi(this.apiClient);
        this.legalEntityWorkLocations = new LegalEntityWorkLocationsApi(this.apiClient);
        this.legalEntityWorkSites = new LegalEntityWorkSitesApi(this.apiClient);
        this.persons = new PersonsApi(this.apiClient);
        this.tenants = new TenantsApi(this.apiClient);
        this.timeOffRequests = new TimeOffRequestsApi(this.apiClient);
    }

}
